version: "3.9"
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: myapp/nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./app:/var/www/html
      - ./logs:/var/log/nginx
    depends_on:
      - php-fpm
    networks:
      - app-network
  php-fpm:
    build:
      context: ./php
      dockerfile: Dockerfile
    image: myapp/php
    volumes:
      - ./app:/var/www/html
      - ./php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - mysql
    networks:
      - app-network
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge