<h1><?= $this->translate('department_employees') ?></h1>

<a class="btn btn-primary" href="<?php echo $this->url('employee_department', ['action' => 'add']); ?>">Add Employee Department</a>

<table class="table table-striped">
    <thead>
    <tr>
        <th>ID</th>
        <th>Employee Name</th>
        <th>Department Name</th>
        <th>Actions</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($entries as $entry): ?>
        <tr>
            <td><?=$entry['id']; ?></td>
            <td><?= $entry['employee'] ?></td>
            <td><?= $entry['department'] ?></td>
            <td>
                <a class="btn btn-info" href="<?= $this->url('employee_department', ['action' => 'edit', 'id' => $entry['id']]); ?>">Edit</a>
                <a class="btn btn-danger" href="<?= $this->url('employee_department', ['action' => 'delete', 'id' => $entry['id']]); ?>" onclick="return confirm('Are you sure you want to delete this employee from this department?')">Delete</a>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
