<h1>Edit Employee</h1>
<div class="container">
    <?php
    $form = $this->form;
    $form->setAttribute('action', $this->url('employee', ['action' => 'edit', 'id' => $this->id]));
    $form->prepare();
    ?>
    <?= $this->form()->openTag($this->form, ['class' => 'form']) ?>
    <div class="form-group">
        <?= $this->formLabel($form->get('full_name')) ?>
        <?= $this->formInput($this->form->get('full_name'), ['class' => 'form-control']) ?>
        <?= $this->formElementErrors($this->form->get('full_name'), ['class' => 'error']) ?>
    </div>
    <div class="form-group">
        <?= $this->formSubmit($this->form->get('submit'), ['class' => 'btn btn-primary']) ?>
    </div>
    <?= $this->form()->closeTag() ?>

    <a href="<?= $this->url('employee', ['action' => 'index']) ?>" class="btn btn-secondary">Back to Employee List</a>
</div>
