<div class="d-flex justify-content-between align-items-center mb-3">
    <h2 class="m-0"><?= $this->translate('employees') ?></h2>
    <a href="<?= $this->url('employee', ['action' => 'add']) ?>" class="btn btn-primary">Add New Employee</a>
</div>
<table class="table table-striped">
    <thead>
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th></th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($this->employees as $employee) : ?>
        <tr>
            <td><?= $employee->getId() ?></td>
            <td><?= $employee->getName() ?></td>
            <td>
                <a href="<?= $this->url('employee', ['action' => 'edit', 'id' => $employee->getId()]) ?>" class="btn btn-info">Edit</a>
            </td>
            <td>
                <a href="<?= $this->url('employee', ['action' => 'delete', 'id' => $employee->getId()]) ?>" onclick="return confirm('Are you sure you want to delete this employee?')" class="btn btn-danger">Delete</a>
            </td>
        </tr>
    <?php endforeach ?>
    </tbody>
</table>