<h1><?= $this->translate('departments') ?></h1>

<div class="table-responsive">
    <table class="table table-hover">
        <thead class="thead-light">
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($departments as $department) : ?>
            <tr>
                <td><?= $this->escapeHtml($department->getId()) ?></td>
                <td><?= $this->escapeHtml($department->getNameRu()) ?></td>
                <td><a class="btn btn-info" href="<?= $this->url('department', ['action' => 'edit', 'id' => $department->getId()]) ?>">Edit</a></td>
                <td><a class="btn btn-danger" href="<?= $this->url('department', ['action' => 'delete', 'id' => $department->getId()]) ?>" onclick="return confirm('Are you sure you want to delete this department?')">Delete</a></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<p><a class="btn btn-primary" href="<?= $this->url('department', ['action' => 'add']) ?>">Add Department</a></p>
