<h1><?= $this->translate('users') ?></h1>
<div class="mb-3">
    <a href="<?= $this->url('user', ['action' => 'add']) ?>" class="btn btn-primary">Add User</a>
</div>
<table class="table table-striped">
    <thead>
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Action</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($users as $user) : ?>
        <tr>
            <td><?= $this->escapeHtml($user->getId()) ?></td>
            <td><?= $this->escapeHtml($user->getName()) ?></td>
            <td>
                <a href="<?= $this->url('user', ['action' => 'edit', 'id' => $user->getId()]) ?>" class="btn btn-info">Edit</a>
                <a href="<?= $this->url('user', ['action' => 'delete', 'id' => $user->getId()]) ?>" onclick="return confirm('Are you sure you want to delete this user?')" class="btn btn-danger">Delete</a>
            </td>
        </tr>
    <?php endforeach ?>
    </tbody>
</table>